release/0.3.0 * major refactoring of http libs * templating libraries * use configured template engine to render yaml templates in flowcontrol

diff --git a/eventFlows/continualFlowControl/src/main/resources/io/continual/flowcontrol/impl/controller/k8s/initDeployment.yaml b/eventFlows/continualFlowControl/src/main/resources/io/continual/flowcontrol/impl/controller/k8s/initDeployment.yaml
--- a/eventFlows/continualFlowControl/src/main/resources/io/continual/flowcontrol/impl/controller/k8s/initDeployment.yaml
+++ b/eventFlows/continualFlowControl/src/main/resources/io/continual/flowcontrol/impl/controller/k8s/initDeployment.yaml
@@ -6,7 +6,11 @@ data:
   sysprep: |
     #!/bin/sh
     echo "Pulling job config from ${CONFIG_URL}..."
-    curl -v -o ${FC_CONFIG_FILE} "${CONFIG_URL}"
+    curl --fail-with-body -v -o ${FC_CONFIG_FILE} "${CONFIG_URL}"
+    if [ $? -ne 0 ]; then
+        echo "Error: curl call failed."
+        exit 1
+    fi
     echo
     echo
     cat ${FC_CONFIG_FILE}
